### ISSUE TITLE
Spamming exceptions when/after installing docking port with KIS

### ISSUE THREAD

**Issue by robert-cassidy** [toadicus/AdaptiveDockingNode#1]
ModuleAdaptiveDockingNode:FixedUpdate throwing out constant exceptions while and after installing clampotron Jr. on derelict craft. Active ship docking port (Kip medium) won't dock with target port after installation, even after resave.

**Comment by toadicus** [comment]
Fixed by 4a04d36b4e123df61c45065f632ca36f169fc507.
