### ISSUE TITLE
Parts won't undock

### ISSUE THREAD

**Issue by robert-cassidy** [toadicus/AdaptiveDockingNode#2]
I have a station with a pair of passive androgynous docks (Kipards mod) and one vessel docked to each with an an active dock. I cannot at this time undock either vessel. The menu item is there but I get the following error in the log:

[WRN 23:36:50.299] [DockingNode]: other node is null!

Now, I've done this successfully some time ago, but it might have been before the last update. I've tried undocking from any of the 4 docks (2 active, 2 passive) and same result. I've restarted the game, etc. No difference. 

KSP 1.0.2, most recent version of ADN from CKAN. Newly re-downloaded KIP adaptive node. Mac OS X 10.10.3. 

I'll poke around and see if I can rule anything else out. Surprised if this has gone unreported for this long.

**Comment by toadicus** [comment]
That's not my error message; that's a Squad error message.  It's possible my plugin is doing something faulty that is causing the other node to be null, but I can't tell without a full log.

**Comment by robert-cassidy** [comment]
Ok, not sure what's going on here. New vessels with the parts work fine, it's possible my save is corrupted. Going to close until I can reproduce.
